#! /bin/bash

while IFS= read -a user ;
do
	total_interest=0
	IFS=$' ' groups=( $(id -nG $user) )
	for group in "${groups[@]}"; do
		a=1
		while IFS= read -a group_name ;
			do 
			if [ $group = $group_name ]
				then 
				var=$(cat Daily_Interest_Rates.txt | sed 's/.$//' | awk 'NR=='"$a"'' | grep -o '.....$')
				result=$(awk "BEGIN {printf \"%.2f\",${var}+${total_interest}}")
				total_interest=$result
			fi
			((a+=1))
		done < <(cat Daily_Interest_Rates.txt | sed 's/.$//' | rev | cut -c6- | rev)
	done
	inp=$(</home/$user/Current_Balance.txt)
	result=$(awk "BEGIN {printf \"%.2f\",${total_interest}*${inp}}")
	echo $(awk "BEGIN {printf \"%.2f\",${result}+${inp}}")>/home/$user/Current_Balance.txt
done < <(cat /etc/passwd | cut -d: -f1 | awk '/UserAcc/ { print }' )
