#! /bin/bash
IFS='/' cur_path=( $(pwd))
b_no=$(echo "${cur_path[2]}" | grep -o '.$')
while IFS= read -a user ; 
        do 
        IFS=$' ' groups=( $(id -nG $user) )
        for group in "${groups[@]}"; do
                if [[ $group =~ Branch ]]
                        then
                        if [ "${group:0 -1}" = $b_no ] 
                        then 
                        var=$(<Branch_Current_Balance.txt)
                        user_bal=$(</home/$user/Current_Balance.txt)
                        echo $(awk "BEGIN {printf \"%.2f\",${var}+${user_bal}}")>Branch_Current_Balance.txt
                        cat /home/$user/Transaction_History.txt >> Branch_Transaction_History.txt
                        fi
                fi
        done
done < <(cat /etc/passwd | cut -d: -f1 | awk '/UserAcc/ { print }' );



