#! /bin/bash
chmod u+x genUser permit 
echo 'alias genUser="./genUser"' >> ~/.bashrc
echo 'alias permit="sudo ./permit"' >> ~/.bashrc
#'$bash -c $"shopt -s expand_aliases; alias updateBranch='sudo su;su - BranchManager1;./updateBranch'\n updateBranch'
#echo 'alias updateBranch="sudo -E su;su - BranchManager1;./updateBranch"' >> ~/.bashrc
#echo 'alias allotInterest="~/bin/createcron"' >> ~/.bashrc
#echo 'alias makeTransaction="sudo su;su - UserAcc1;./makeTransaction"' >> ~/.bashrc

